name: xrosswall
base: core24
adopt-info: v2ray
license: Apache-2.0
summary: xrosswall = caddy + v2ray
description: |
  A simple solution, combining caddy and v2ray, for anti-censorship. 

platforms:
  amd64:
  arm64:

grade: stable
confinement: strict

apps:
  xrosswall:
    command: bin/run-helper

  caddy:
    command: bin/caddy run --config $SNAP_DATA/Caddyfile
    reload-command: bin/caddy reload --config $SNAP_DATA/Caddyfile
    stop-command: bin/caddy stop
    restart-condition: always
    daemon: simple
    plugs:
      - network
      - network-bind

  v2ray:
    command: bin/v2ray run --config $SNAP_DATA/config.json
    restart-condition: on-failure
    daemon: simple
    plugs:
      - network
      - network-bind
parts:
  misc:
    plugin: dump
    source: conf/
    organize:
      Caddyfile.tpl: conf/
      config.json.tpl: conf/
      run-helper : bin/run-helper
    stage-packages:
      - gettext

  caddy:
    plugin: go
    build-snaps:
      - go
    source-type: git
    source: https://github.com/caddyserver/xcaddy
    source-tag: 'v0.4.4'
    source-depth: 1
    override-build: |
      craftctl default
      $CRAFT_PART_INSTALL/bin/xcaddy build \
        --with github.com/caddy-dns/cloudflare \
        --with github.com/caddy-dns/azure \
        --with github.com/caddy-dns/linode \
        --with github.com/caddy-dns/namecheap \
        --with github.com/caddy-dns/route53 \
        --with github.com/caddy-dns/duckdns \
        --with github.com/caddy-dns/vultr \
        --with github.com/caddy-dns/godaddy \
        --output $CRAFT_PART_INSTALL/bin/caddy
    stage:
      - -bin/xcaddy

  v2ray:
    plugin: go
    build-snaps:
      - go
    source-type: git
    source: https://github.com/v2fly/v2ray-core
    source-tag: 'v5.29.1'
    source-depth: 1
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0 | tr -d 'v')
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/bin
      export CGO_ENABLED=0
      cd $CRAFT_PART_SRC && go build -o $CRAFT_PART_INSTALL/bin/v2ray -trimpath -ldflags "-s -w -buildid=" ./main
